### ISSUE TITLE
Deploy topic controller automatically with the cluster

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#119]
Currently the Topic Controller has to be deployed on its own. We should make it possible to deploy it automatically through the Cluster Controller.

**Comment by ppatierno** [comment]
Because the topic controller needs to connect to Zookeeper and Kafka cluster, I guess that this issue can be fixed after the #118 because the cluster controller has to be sure that Zookeeper is running in order to deploy Kafka cluster (for avoiding pods restarts) and then deploying the topic controller when the Zookeeper+Kafka cluster is ready.

@scholzj @tombentley wdyt ?

**Comment by scholzj** [comment]
@ppatierno Yeah, lets wait for #118

**Comment by ppatierno** [comment]
I have started to take a look into this issue, following some thoughts about configuring the TC.

The TC (deployed by CC) needs some configuration parameters that are provided by env vars in the current YAML file. This env vars should be "filled" by CC when it's going to create the `Deployment` for the TC in the following way : 

- `STRIMZI_NAMESPACE` should be the same where the Kafka + Zk cluster were deployed. TC doesn't work across namespaces.
- `STRIMZI_KAFKA_BOOTSTRAP_SERVER` and `STRIMZI_ZOOKEEPER_CONNECT` are well know by the CC because it created the cluster :-)
- `STRIMZI_FULL_RECONCILIATION_INTERVAL` is something that we already have for the CC reconciliation even if in a different format (number 60000 as milliseconds against "30seconds" format). We can use the same interval for both reconciliation but maybe having fine granularity with different ones could be better.
- `STRIMZI_CONFIGMAP_LABEL` is well known
- `ZOOKEEPER_SESSION_TIMEOUT` could be something to be configurable

Having something configurable for the TC means having such a configuration in the cluster ConfigMap. Maybe we could use the same approach for other components (i.e. metrics) with a data field named `topic-controller-config` and a JSON for its configuration (i.e. zookeeper session timeout, ...).

Finally, I think that we should have TC deployed by CC as optional but "true" by default (maybe not having the `topic-controller-config` data filed could mean not deploying the TC, as already happens for enabling/disabling metrics).

Regarding the need for ServiceAccount, ClusterRole and RoleBinding creation they are not supported by the current fabric8 Kubernetes client and going through raw HTTP requests against the Kubernetes API server seems to be one solution (as already done by EnMasse team).

What they (EnMasse) do is having service accounts and cluster roles created up front using the deployment script (which uses some YAML resoureces file) and the address-controller just creates the needed role-binding. In our case having them created up front could not work if we have the possibility to deploy the TC not from the CC; the current YAML file would try to create already existing resources.

@scholzj @tombentley any thoughts ?

**Comment by tombentley** [comment]
> STRIMZI_CONFIGMAP_LABEL is well known

The CC one is the label(s) defining which labels select CC CMs. The TC has its own CMs, so needs its own selector, no?

> Having something configurable for the TC means having such a configuration in the cluster ConfigMap.

If we take this approach would that mean that every time we want a new config in the TC we have to also add support in the CC? I suppose you could treat such config as opaque to the CC (which is what we do for metrics), but that means validation only happens when we get to the TC. That's not essential, but it would be nicer if the CC could detect a problem with the CM sooner.

**Comment by ppatierno** [comment]
@tombentley what I meant is that TC labels to watch are well defined as `strimzi.io/kind=topic` so no need for an external configuration or ... we could provide a way to change it to the user so configuration is needed as well.

**Comment by scholzj** [comment]
Yeah, I think having the possibility to switch it on/off should be there. An additional configuration similar to storage might make sense (Docker image, timeouts, namespace? etc.). 

The question is how do we deal with the namespaces and roles. Should the user be able to configure in which namespace to watch for topics / create topics? Should these namespaces be different from the CC namespaces?

If we want to save us the troubles of the role and binding creation, we can also deploy it under the CC service account. That should have already all the needed rights (but it has some additional rights not needed for TC). It would save us needing the rights for creating roles and bindings.

**Comment by ppatierno** [comment]
Using the storage approach could provides what @tombentley asked, so a validation before having parameters passed to the TC.

If the CC is configured to watch for one or more namespaces, the user could create CMs for these namespaces and a new Kafka + Zk cluster is deployed for each of them; as far as I understood we want a TC for each namespace so yes ... the namespaces should be the same as the CC ones. Is it what you mean @scholzj ?

**Comment by scholzj** [comment]
> Using the storage approach could provides what @tombentley asked, so a validation before having parameters passed to the TC.

We will not pass the entire TC configuration through the CC config map. Just some of the things. As I mentioned, following things come to my mind:
* Docker image
* Mamespace to watch
* ZK timeout / reconciliation interval
* namespaces???

But we would not allow to configure things like:
* Labels
* ZK URL
* Bootstrap URL

> If the CC is configured to watch for one or more namespaces, the user could create CMs for these namespaces and a new Kafka + Zk cluster is deployed for each of them; as far as I understood we want a TC for each namespace so yes ... the namespaces should be the same as the CC ones. Is it what you mean @scholzj ?

Well ... I can imagine that I want to run my Kafka cluster in namespace `proc-project-a-kafka` and my clients (with the topic config maps) in `prod-project-a`. So there might be a need to configure tha namespace separately. I can also see a case where you would need to watch multiple namespaces.

**Comment by ppatierno** [comment]
@scholzj yes agree maybe it wasn't clear that we are on the same page :-) PS : is "Namespace to watch" something different from "namespaces???". ?

> Well ... I can imagine that I want to run my Kafka cluster in namespace proc-project-a-kafka and my clients (with the topic config maps) in prod-project-a. So there might be a need to configure tha namespace separately. I can also see a case where you would need to watch multiple namespaces.

So you mean having the TC deployed in the same namespace as the Kafka + Zk cluster but watching for CMs in different namespaces right ?

**Comment by scholzj** [comment]
> "Namespace to watch" something different from "namespaces???"

Yeah, it might need to be more namespaces, but just once. It seems that I'm creating duplicates and damaging payload :-).

> So you mean having the TC deployed in the same namespace as the Kafka + Zk cluster but watching for CMs in different namespaces right ?

Yeah, the TC should run in the namespace where the cluster runs. That could be probably hardcoded. But the namespace(s) to watch might be different. Sorry for not being precise.

**Comment by ppatierno** [comment]
So regarding configurable parameters for the topic controller using the JSON (as for storage) is the way to go but instead of re-write something similar to the `Storage` class it could be helpful to re-use the `Config` class from the topic-controller maybe adding methods for handling the JSON format. @tombentley wdyt about that ?

Finally, regarding cluster roles I would start using the same service account as the cluster controller and changing it later if needed.

**Comment by scholzj** [comment]
> So regarding configurable parameters for the topic controller using the JSON (as for storage) is the way to go but instead of re-write something similar to the Storage class it could be helpful to re-use the Config class from the topic-controller maybe adding methods for handling the JSON format.

The parameters will be different ... so you IMHO cannot reuse anything from TC.

**Comment by ppatierno** [comment]
Zookeeper connect timeout, reconciliation, namespaces are there ... Docker image is not there and it should not be in the `Config` TC class but maybe we could derive a new class to use in the CC. Just thinking aloud to avoid duplication ...

**Comment by ppatierno** [comment]
Deploying the topic-controller is part of the `KafkaClusterOperations` as it already happens to Zookeeper. After deploying Zookeeper and the Kafka, the operations should deploy the topic controller.

In order to have the topic-controller deployment fitting into the current cluster-controller architecture we should think the topic-controller to be implemented as a possible derived class from `AbstractCluster` and a related `AbstractClusterOperations`.

It sounds strange to me because it's not a cluster and a lot of stuff in the `AbstractCluster` class doesn't make sense for just the topic-controller. At same time it's also true that it needs getting configuration from the cluster CM as we do within the `fromConfigMap` for the other "clusters".

One idea for having a separation not having the topic-controller as a deployment inside the Kafka operations could be having the `create` method from `AbstractClusterOperations` allowing to pass and handler so that when "create" is finished, the topic controller deployment can start from within the `ClusterController` class but using a different operation and not the cluster one.

In any case maybe we change the "Cluster" naming that we have in these resources and operations because we are going to deploy something which is not a cluster anymore ? I know that "Deployment" drives to think about the K8S deployment resource but it's more general than cluster.

@tombentley @scholzj what are your thoughts about my .... mumbling :)

**Comment by scholzj** [comment]
My original implementation of S2I had a resource which was not extending `AbstractCluster`. It simply had the methods to generate the OpenShift resources, to diff and to instantiate from JSON (i.e. the sub-section from the kafka cluster config map) or from OpenShift directly. And than it had its own Operation. 

But I felt it was not that straight forward to use it. So maybe integrating it directly into `KafkaCluster` would be better. You can add methods such as `generateTopicControllerDeployment`, extend `diff`, `fromStatefulSet` and `fromConfigMap` etc. and call them directly from the `KafkaClusterOperation`. But maybe Tom comes up with something smarter.

**Comment by ppatierno** [comment]
It's a possibility but I see the topic controller deployment closely related to the Kafka cluster in this way. It's true for the Zookeeper cluster as well but it maintains a sort of "independence" thanks to the 'ZookeeperCluster` and related operations classes that we have still there. In both cases, the Kafka operations orchestrate their deployment.

I would have something like that so separated classes as your first approach with S2I but at same time trying to follow the pattern that @tombentley has put in place in the cluster controller.

**Comment by tombentley** [comment]
I agree the term Cluster isn't really right in the AbstractClusterOperations hierarchy. Really those higher-level operations are about coordinating a collection of lower levels resources. It happens that until now those some of those resources have been clusters. `Component` doesn't seem an ideal fit, but is perhaps better than `Deployment`, which would cause too much confusion if we overloaded it to mean something other than its meaning in k8s.

In the `AbstractCluster` hierarchy those things are about representing desired and current states of the "components". Again, there is nothing particularly "clusterful" about them, aside from the fact that until now those states have been the states of components that formed clusters.

To me, on the face of it, I would manage the topic controller similarly to how the zookeeper cluster is managed within the KafkaClusterOperations, at least until I understood exactly why that didn't work.

**Comment by ppatierno** [comment]
Agree that `Deployment` doesn't fit great due to the K8S deployment resources ... `Component` should work better.
So in order to avoid a big PR with a log of changes I'll open a PR with these naming changes first, moving from "Cluster" to "Component" for all the classes.
Then the topic controller will follow the new `AbstractComponent` hierarchy and its deployment will be handled as the Zookeeper one.

**Comment by ppatierno** [comment]
closed by #237
