### ISSUE TITLE
Inconsistent "cluster-name" and "name" labels values

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#158]
Currently we have a couple of labels which are `cluster-name` and `name` which : 

1. don't follow the "new" format with Strimzi domain
2. they get wrong values in some cases

For point 1) we have to move to have `strimzi.io/cluster` (instead of just `cluster-name`) and `strimzi.io/name` (instead of just `name`)

For point 2) the `cluster-name` needs to be always the name of the cluster specified in the provided cluster ConfigMap (i.e. `metadata.name` from the cluster ConfigMap). It's useful to the user for getting resources belonging to the same cluster. The following example reports a wrong value for the `cluster-name` when the cluster is named "kafka".

`oc get service kafka-zookeeper -o yaml`

selector:
    cluster-name: kafka-zookeeper
    name: kafka-zookeeper
    strimzi.io/kind: cluster
    strimzi.io/type: zookeeper

Always for point 2) the `name` is mostly used for the services selector.

We should also check that for every resources the `metadata.name` is equal to the `strimzi.io/name` labels.

**Comment by ppatierno** [comment]
> How does the name or strimzi.io/name label differ from the metadata.name?
This is a bug we have currently in the cluster controller. It doesn't make sense they are different.

> If, as you say, they should always be equal, then why not just select these things by name?
Do you mean, why not just selecting using `metadata.name` ? Metadata info can't be used for selection, only labels can be used for that.

> But if it really is necessary and if the name is mostly used for selecting services wouldn't something like strimzi.io/service on services be more clear?
Because service selector works on label, it can be called as you want but in my experience `name` label is mostly used for this. Btw if you think from service to pods you say "this service is related to all pods which match these labels (i.e. name=zookeeper)"; in this case imho it doesn't make more sense call the label "service".

**Comment by scholzj** [comment]
AFAIK the selectors work only against labels. So they cannot user metadata.name. Also right now, the `metadata.name` is not always the same as the label, because the `metadata.name` often uses something as `kafka-zookeeper-1` where the label is only `kafka-zookeeper`. (The selectors are not only in services, they are also in StatefulSets (AFAIK mandatory from v1 etc.) 

Maybe we can replace `strimzi.io/name` with something better ... but I think we need something like this. The problem is that if we want to replace it with something more semantically correct, it would be different for different resources and make our SW more complex.

**Comment by ppatierno** [comment]
I have taken a look at how we assign the `name` label today for different resources.
Following SS = StatefulSets, PODS, SVC = Services, CM = ConfigMap and <CN> is the ClusterName so `metadata.name` in the cluster ConfigMap.

SS Kafka = <CN>
SS Zookeeper = <CN>-zookeeper
PODS Kafka = <CN>-x (where x is the index assigned by K8S/OS)
PODS Zookeeper = <CN>-zookeeper-x
SVC Kafka = <CN>
SVC Kafka headless = <CN>-headless
SVC Zookeeper = <CN>-zookeeper
SVC Zookeeper headless = <CN>-zookeeper-headless
CM cluster = <CN>
CM Kafka metrics = <CN>-metrics-config
CM Zookeeper metrics = <CN>-zookeeper-metrics-config

I'm ok with the suffix we are using today (i.e -zookeeper, -zookeeper-headless, ...) but I'd like to have a suffix for the "kafka" as well which is something radanalytics.io team is using. For example if you create a Spark cluster named "my-cluster" they have my-cluster-m (for the master nodes) and my-cluster-w (for the worker nodes). On our side we could have my-cluster-kafka (instead of just my-cluster as today) for the Kafka cluster and leaving as it is my-cluster-zookeeper for the Zookeeper cluster. Maybe we can use something like "zk" and "kf" instead of long names.

@scholzj @tombentley wdyt ?

**Comment by scholzj** [comment]
@ppatierno I think it depends on the name for the cluster. `my-cluster-kafka` sounds good. `my-kafka-kafka` or `kafka-kafka` looks strange. What about using `-broker` as suffix for Kafka instread of `-kafka`?

**Comment by tombentley** [comment]
> PVC Kafka = kafka-storage-[CN]-x (where x is the index assigned by K8S/OS)
> PVC Zookeeper = zookeeper-storage-[CM]-zookeeper-x (where x is the index assigned by K8S/OS)

The inconsistency here (and the double zookeeper) is ugly.

**Comment by ppatierno** [comment]
@scholzj fine with me about using `-broker`, the main point to me is not just using `my-cluster` to identify the Kafka cluster.

**Comment by ppatierno** [comment]
@tombentley the first part (so XXXX-storage) is related to the volumeClaimTemplate used in the StatefulSets which is the volume name. The rest should be added automatically from the StatefulSets in relation to the Pod (names) which will use the volume.

**Comment by tombentley** [comment]
@ppatierno so the asymmetry originates here:

> SS Kafka = [CN]
> SS Zookeeper = [CN]-zookeeper

? Maybe we should change the Kafka SS name to "[CN]-kf" (and zookeeper one to "[CN]-zk"), so it's more consistent: I mean there's no particular reason to priviledge the kafka SS, is there?

We also need to bear in mind that we'll end up with some topic controller pods, so I guess we could add:

PODS Topic-controller = [CN]-tc-x

wdty?

**Comment by ppatierno** [comment]
@tombentley  it's exactly what I was suggesting in the previous comment : 

> I'm ok with the suffix we are using today (i.e -zookeeper, -zookeeper-headless, ...) but I'd like to have a suffix for the "kafka" as well which is something radanalytics.io team is using. For example if you create a Spark cluster named "my-cluster" they have my-cluster-m (for the master nodes) and my-cluster-w (for the worker nodes). On our side we could have my-cluster-kafka (instead of just my-cluster as today) for the Kafka cluster and leaving as it is my-cluster-zookeeper for the Zookeeper cluster. Maybe we can use something like "zk" and "kf" instead of long names.

then @scholzj mentioned the following : 

> I think it depends on the name for the cluster. my-cluster-kafka sounds good. my-kafka-kafka or kafka-kafka looks strange. What about using -broker as suffix for Kafka instread of -kafka?

**Comment by scholzj** [comment]
> I mean there's no particular reason to priviledge the kafka SS, is there?

@tombentley Actually, it is. We do Kafka as a service, not Zookeeper as a service. Zookeeper is there only because it is a dependency for Kafka. So that builds in my view some kind of hierarchy. It is similar to the discussion we had yesterday about the one release package (Kafka) instead of 2 release packages (Kafka + Zookeeper).

But I'm fine with the suffix for both. But we should think it through:
- I really think that `-kafka` is not suitable because kafka might be already in the cluster name for many people
- I personally would probably prefer longer names than shortcuts which most people will not get (when I see `tc` the first thinkg for me is still technical committee :-)). But this is is just my personal view.
- If we rename the Statefulsets - we should probably also rename the services. So we should think about their names as well ... see #55

**Comment by tombentley** [comment]
>  We do Kafka as a service, not Zookeeper as a service.

* That's true today, but perhaps not always. 
* Personally, I would prefer consistency and the self-describing nature of [CN]-kafka over [CN]

> I really think that `-kafka` is not suitable because kafka might be already in the cluster name for many people

I don't find that a particularly strong argument, because:

* It's avoidable with good documentation
* Even if/when it does happen it's hardly the end of the world

I think the consistency in naming that this brings elsewhere would be more valuable.

> I personally would probably prefer longer names than shortcuts which most people will not get

I can live with longer names, but if we're expecting people to be typing these things by hand then there is something to be said for shorter names.

Overall I think this whole conversation points to the need to document these naming choices well (somewhere outside of this issue).

**Comment by ppatierno** [comment]
@scholzj @tombentley I'm going to use long name and `-kafka` (I think it's clearer than just `-broker`, as we are using `-zookeeper`) as a suffix for now. If it won't work it will be just a matter of changing a constant in the code ;)

**Comment by scholzj** [comment]
@ppatierno What about the KAfka Connect? I think you should deal with that as well ... perhaps with `-connect` or `-kafka-connect`.

**Comment by ppatierno** [comment]
@scholzj I would go just for `-connect` in this case.

**Comment by ppatierno** [comment]
Closed by #163
