### ISSUE TITLE
Use official Grafana image and provide OpenShift template

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#160]
Instead of relaying on this [project](https://github.com/OpenShiftDemos/grafana-openshift) for providing a Grafana image on Kubernetes and OpenShift (with a template), it could be worth to try the [official Grafana image](https://hub.docker.com/r/grafana/grafana/) and providing OpenShift template from Strimzi repo.

**Comment by scholzj** [comment]
The investigation of the official Grafana image has been done by @serrss in #318 ... the image doesn't work properly on OpenShift for us due to permission issues.

In the same PR we also decided that since Prometheus and Grafana are not official deliveries for us, we should not maintain the templates for them and have just simple YAML files. This issue can be closed.
