### ISSUE TITLE
Generate new 0.x release with CentOS7 base image instead of Fedora26

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi#245]
Generate new 0.x release with CentOS7 base image instead of Fedora26 since the CentOS7 base image is more common and more stable.

**Comment by scholzj** [comment]
In master, we already updated to CentOS 7. We hope to do a 0.2.0 release towards the end of this week / beginning of next week. You can follow our us on GitHub or on our [mailing list](https://www.redhat.com/mailman/listinfo/strimzi) to be informed about the release.

Out of curiosity - did you had any problems using our Fedora based images in 0.1.0? Or was this just a general comment?

**Comment by ron1** [comment]
I had no problems with the Fedora-based image. It's just that CentOS7-based images are often preferred over Fedora-based images in many environments.

Will the 0.2.0 release continue to support deployment of traditional kubernetes/openshift artifacts as in 0.1.0?

**Comment by ppatierno** [comment]
The 0.2.0 release will provide a way to deploy the Kafka cluster through the "operator" approach. A cluster controller needs to be deployed in the Kubernetes/OpenShift cluster and then providing a single ConfigMap with the Kafka cluster configuration, it's able to deploy such a cluster (the same for deploying a Kafka Connect cluster). Alongside with the cluster controller, a topic controller is deployed in order to manage topics : you can create a Kafka topic, just creating a ConfigMap containing topic configuration and the topic controller, watching for such ConfigMaps, will create the corresponding topic in the Kafka cluster. The same is true on deletion : deleting the topic ConfigMap will delete the topic.
You can find more info in the master branch for now before the official 0.2.0 release. The current YAML files will be more "examples" than the official way for deploying the Kafka cluster.

**Comment by scholzj** [comment]
> I had no problems with the Fedora-based image. It's just that CentOS7-based images are often preferred over Fedora-based images in many environments.

I agree ... this is exactly why I changed it to CentOS :-)

**Comment by ron1** [comment]
The "operator" approach is a much-welcomed feature but I would like to give it significant time to mature before I use it for real work. In the meantime, can either 0.2.0 be made to support the traditional deployment model or can a CentOS7-based 0.1.1 version be released that continues to support the traditional deployment model?

**Comment by scholzj** [comment]
To be honest I'm not sure whether it is worth doing 0.1.1 if you actually don't have any problems with Fedora.

**Comment by ron1** [comment]
Obsoleted by issue https://github.com/strimzi/strimzi/issues/319.
