### ISSUE TITLE
Improve Cluster Controller resiliency

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#264]
Cluster Controller today cannot handle situations when some of the resources are deleted after the cluster was created. It seems that it cannot handle this neither when updating cluster nor when deleting them. We should improve the resilience:
- Delete should work in all cases
- Update should be ideally able to recreate the resources

**Comment by asorokhtey** [comment]
I've found an issue and it can be related to this one.
Steps to reproduce:
1. Clone and open Strimzi sources https://github.com/strimzi/strimzi
Up cluster
$ oc clucter up
2. Login as admin
$ oc login -u system:admin
3. Deploy Cluster Controller
$ oc create -f examples/install/cluster-controller
$ oc create -f examples/templates/cluster-controller
4. Set STRIMZI_FULL_RECONCILIATION_INTERVAL_MS variable to 3000
5. Login to OpenShift https://127.0.0.1:8443
Create "Apache Kafka (Persistent storage)"
5.1 Click "Add to project"
5.2 Click "Select from project"
5.3 Select "Apache Kafka (Persistent storage)" and click "Next"
5.4 Use default configurations:
Number of Zookeper cluster nodes: 3
Number of Kafka cluster nodes: 3
5.5 Click "Create" and wait for the message "Apache Kafka (Persistent storage) has been created"
5.6 Open page "Pods" and wait when all pods will have status "Running"
6. Go to Applications >> Pods>> strimzi-cluster-controller-  >>logs
See that there are NPE in logs
```
2018-03-06 12:35:57 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
--
  | 2018-03-06 12:35:57 INFO  AbstractClusterOperations:236 - Reconciling Kafka clusters ...
  | 2018-03-06 12:35:57 INFO  AbstractClusterOperations:248 - Reconciliation: Kafka cluster my-cluster should be checked for updates
  | 2018-03-06 12:35:57 INFO  AbstractClusterOperations:249 - Checking for updates in Kafka cluster my-cluster
  | 2018-03-06 12:35:57 INFO  KafkaClusterOperations:615 - Updating Zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-06 12:35:57 INFO  AbstractClusterOperations:148 - update zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-06 12:35:57 INFO  AbstractClusterOperations:158 - zookeeper cluster my-cluster-zookeeper in namespace myproject: successful update
  | 2018-03-06 12:35:57 INFO  KafkaClusterOperations:436 - Updating Kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-06 12:35:57 ERROR AbstractClusterOperations:150 - Error while getting required kafka cluster state for update operation
  | java.lang.NullPointerException
  | at io.strimzi.controller.cluster.resources.KafkaCluster.diff(KafkaCluster.java:210)
  | at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations$7.getCluster(KafkaClusterOperations.java:439)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.execute(AbstractClusterOperations.java:147)
  | at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations.lambda$update$5(KafkaClusterOperations.java:692)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$execute$0(AbstractClusterOperations.java:159)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.execute(AbstractClusterOperations.java:156)
  | at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations.update(KafkaClusterOperations.java:688)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$reconcile$4(AbstractClusterOperations.java:250)
  | at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  | at java.lang.Thread.run(Thread.java:748)
  | 2018-03-06 12:35:57 ERROR AbstractClusterOperations:254 - Failed to update Kafka cluster my-cluster.
```

**Comment by scholzj** [comment]
@asorokhtey I think that the log is too short to say for sure that it is related. To you have the full log?

**Comment by asorokhtey** [comment]
@scholzj here is full log file [logfile.txt](https://github.com/strimzi/strimzi/files/1785029/logfile.txt)

**Comment by scholzj** [comment]
Yep, this is the same issue:
```
2018-03-06 11:34:47 INFO  AbstractOperations:189 - Waiting for Pods resource my-cluster-zookeeper-0 in namespace myproject to get ready
2018-03-06 11:34:47 INFO  AbstractOperations:189 - Waiting for Pods resource my-cluster-zookeeper-1 in namespace myproject to get ready
2018-03-06 11:34:47 INFO  AbstractOperations:189 - Waiting for Pods resource my-cluster-zookeeper-2 in namespace myproject to get ready
2018-03-06 11:35:47 ERROR AbstractOperations:220 - Exceeded timeoutMs of 60000 ms while waiting for Pods my-cluster-zookeeper-0 in namespace myproject to be ready
2018-03-06 11:35:47 ERROR AbstractOperations:220 - Exceeded timeoutMs of 60000 ms while waiting for Pods my-cluster-zookeeper-1 in namespace myproject to be ready
2018-03-06 11:35:47 ERROR AbstractOperations:220 - Exceeded timeoutMs of 60000 ms while waiting for Pods my-cluster-zookeeper-2 in namespace myproject to be ready
2018-03-06 11:35:47 ERROR AbstractClusterOperations:161 - zookeeper cluster my-cluster-zookeeper in namespace myproject: failed to create
```

**Comment by scholzj** [comment]
I think there are two problems:
1) If a some resource exists (for example some left-over service) when a cluster is being created, the creation process will never update it. I.e. for any already existing resource, create has to make sure that the resources is either deleted and recreated or updated.
2) If update is missing some resource, it will fail to update it, but not create it.

Unfortunately, both of these are fairly complex operations and cannot be fixed easily. If you patch some existing resource when creating the cluster you would also need to implement the logic to find out whether for example rolling update is needed after the patch operation. The same is valid also in update - different resources are needed at different points of the update operation (e.g. scale-down will need the stateful set and services to work properly). Also the diff it self cannot be done without some of the resources.

So it seems to me that the fix for this which makes most sense is to always chain the create and update operations. I.e. everytime we think we need to create a cluster, we would run `create` followed immediately by an `update`. Everytime we think we need an update, we would first run `create` followed by the `update`. These operations should not take too much time if they actually not do anything, so I do not expect there any significant problems in the cluster taking muhc longer to create or to update.

This could be done either on the level of the `reconcile` method where we would just chain the futures. Or we can do it in the operations by merging the `update` and `create` methods into a single `createOrUpdate` method.

WDYT @tombentley @ppatierno ?

**Comment by ppatierno** [comment]
I agree on the overall idea so ...

1.  `create` + `update` should "fix" already existing K8S resourcers (as you mentioned a left-over service for example)

1.  `update` + `create` should "fix" scenarios where the initial creation went wrong (i.e. the typical case we are having with ZK deployed but then operation timeout ... and Kafka is not created) but the next reconcile is able to update what already exists and create what doesn't exist.

Regarding scenario 1) ...

As the problem we are having with operation timeout, if we create ZK but creating Kafka fails (due to operation timeout) the update step is not executed right ? We have in any case waiting for the next reconciliation (happening with scenario 2)) in order to create the Kafka cluster (then the TC if configured).
In this specific situation, what I see is that the user has to wait a reconciliation period for having the entire cluster working. Or .. if he doesn't want to wait, he has to delete the cluster CM (deleting the half deployed cluster, only Zk) and then re-creating it.
I was wondering if retrying after a while but before a reconciliation for creating the missed Kafka cluster (after an operation timeout) could make sense ? We know that the entire creation process isn't finished well and we know the reason.

Just thinking aloud ...

**Comment by scholzj** [comment]
@ppatierno I think retrying outside of reconciliation would just introduce complexity without helping the cause too much. See it like this ... right now our default reconciliation timeout is 2 minutes. The creation timeout is 5 minutes. 

So at least two reconciliations would be started while waiting for the creation. In many cases, one would be already waiting for the lock and thus start immediately after the failure of the first creation and retry. In the worst case scenario the last reconciliation which was started during the creation has just timeouted (after 1 minute waiting for lock) and the next one will be started in ~1 one minute.

I think these are good numbers and doing something more would add a lot of complexity while improving the timing only marginally.

PS: To be honest ... this is why I think that once we fix this, we should move the timeout for the creation again back to 1 minute, because it will do less waiting and more retrying.

**Comment by ppatierno** [comment]
I didn't take a look to the real numbers, it makes sense.

**Comment by tombentley** [comment]
I agree with the basic idea @scholzj. I think we should pay attention to some important details:

* `AbstractOptionations.create()` has a test-then-createOrReplace strategy, which means there's a race (at least in principle). I'm not sure what happens if we replace a statefulset or deployment (as part of an improved update I mean): Would it result in a rolling update? Perhaps we should do a create unconditionally and let the higher-level cluster operation decide what to do if the resource already exists (thus ensuring we always patch). 

* Likewise `AbstractOptionations.delete()` tests first, so again there can be a race. I did an experiment with fabric8 with CMs and it seems it doesn't throw an exception if you delete a CM which doesn't exist. Maybe we should just delete it unconditionally.

* When updating we do scale down then rolling update then scale up, but scale down doesn't ensure that the SS has the given number of pods, just that it doesn't have *more* than that number. But rolling update assumes all the pods exist (that if the ss was scaled down further behind our backs?). We should also account for a pod being down (e.g. due to crash) in rolling update.

**Comment by scholzj** [comment]
For unconditional create we would need to check what it actually does. The unconditional delete sounds good, although at some point we might need to _synchronize_ the deletion and than it would matter again.

TBH, I do not want to disregard your scenarios ... they are all real and might cause some problems. But I think we need to plug the big holes first and leave the small ones (with fairly low probability) for later. At least unless you have a simple solution to fix them all with single patch. I think that most of these cases might get fixed by next loop. Which might be good enough for us right now. 

Or do you see any major issues with them?

**Comment by tombentley** [comment]
I don't see major issues with them, and I agree they're smaller holes. 

What bothers me is that we're using the periodic reconciliation as a crutch, hoping it will make things right next time it runs, when in fact the problem is in the way we're trying to update the cluster. We've forced ourselves into a pattern where we compute this coarse-grained monlithic diff and then act on that, and we have separate operations for create, update and delete. 

By "coarse gained" I mean stuff like `diff.isDifferent()` guarding the patching of the headful and headless services, and the statefulset. In reality it could be that `isDifferent()` is true simply because the labels of the SS were wrong, but we decide we should patch the service anyway. (In reality I ~expect~ hope something down the line will realise the patch on the services is a noop and not actually touch them). 

I don't think the separation of `*ClusterOperations` from the `*Cluster` is really helping here, as it forces us into trying to precompute what action to take. We shouldn't assume that the resources are in any particular state, and so the action to take depends on the state we find them in. That would suggest that the process of computing a diff is the wrong path to take, and we should seek instead a common finer-grained *CreateOrUpdate* mini-operator approach for each resource. 

A key thing you've established is that create and update should really be the same thing and that suggests we shouldn't have separate operations for them in the code.
