### ISSUE TITLE
Unit tests should be executable individually in IDE

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#277]
All unit tests should be executable one by one from the IDE. This currently doesn't seem to be possible. As an example, trying to run test `testReconcile` in `KafkaClusterOperationsTest` in IntelliJ IDEA seems to end with following error:

```
java.lang.Exception: No tests found matching Method testReconcile(io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperationsTest) from org.junit.internal.requests.ClassRequest@6f75e721

	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

**Comment by tombentley** [comment]
This is because `KafkaClusterOperationsTest` is a parameterized test, and the IDE's runner doesn't understand how to run it with a particular set of parameters. We could make it a normal (unparameterized) test, but to retain the existing coverage that would require expanding out the 2×2×3×3=36 different parameter combinations. Now certainly those parameters happen to be more or less orthogonal, but that still means 2+2+3+3=10 different tests for broadly equivalent coverage.

**Comment by scholzj** [comment]
Is there really now way how to setup some default parameters or something like that? That sounds like a quite omission. :-(

But if we cannot do anything with it, the value of testing with different parameters is for sure higher than running these tests individually.

**Comment by tombentley** [comment]
I believe Eclipse can do it, but it seem intellij cannot, which is a shame.
