### ISSUE TITLE
Storage docs are (too) hard to find

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#333]
I went to http://strimzi.io/docs/master/ looking for docs on the storage. There's nothing in the ToC. I guessed and went to http://strimzi.io/docs/master/#kafka_config_map_details and although the bullet list there does give `kafka-storage` it says to see the related section (no link direct to it, so I don't know where it is, before or after where I am in the doc?) I guessed again and a few pages down is the section for the config, but the section title renders *smaller than the body text*.

We need to make it easier to find this sort of thing:

* Should the ToC go deeper?
* We should link direct to the section.
* We need to ensure that lower level section headings are more noticeable than body text.

**Comment by scholzj** [comment]
> Should the ToC go deeper?

This should be fairly trivial. Just a change of the config in docu.adoc.

> We should link direct to the section.

Where would you link to it from?

> We need to ensure that lower level section headings are more noticeable than body text.

For this you will need to play with the CSS styles of the website. Or we would need to choose some other style for the documentation and not frame it into the website design.

**Comment by stanlyDoge** [comment]
@scholzj The link is added in your PR (https://github.com/strimzi/strimzi/pull/394). Can be this closed?

**Comment by scholzj** [comment]
Well, @tombentley had some other comments as well ... about the styling and the ToC depth. I think that I increased the ToC depth as part of the branding PR. In master, storage is now in the ToC.

So the styling is the only point left. The _Storage_ title is still in a font with half the size. I suggested to stop embeding the docu because the styled asciidoc output is more readable. But @ppatierno didn't like that. Up to @tombentley what he things whether this should be closed or not.

**Comment by stanlyDoge** [comment]
I have enlarged H5 font in another PR (strimzi.github.io repository).

**Comment by scholzj** [comment]
@tombentley please have a look at it (when you have time) ... I think it can be closed.

**Comment by scholzj** [comment]
I'm closing this issue since no feedback has been received for more than 10 days. Feel free to reopen it if you still feel like something is missing.
