### ISSUE TITLE
Explore options for metrics & monitoring

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#42]
How do we expose the Kafka and ZooKeeper metrics & monitoring within barnabas?

**Comment by tombentley** [comment]
A couple of monitoring idea from netflix: https://medium.com/netflix-techblog/kafka-inside-keystone-pipeline-dd5aeabaf6bb#1f2d

**Comment by ppatierno** [comment]
After some exploration, following what I have learned about this topic.

As you already know we can use the JMX Exporter for Prometheus in order to get Kafka JMX metrics. Such exporter can be used in two different ways : 

- as Java agent : it means that in each Kafka broker pod we have one container with both Kafka running and the related agent connected to the JVM for getting all system and Kafka wide metrics
- as standalone component : it means that the exporter can be used inside a "sidecar" container on the same pod of the Kafka broker. It connects to the JMX metrics via URL (i.e. localhost:9999 exposed by the Kafka broker).

In both solution, the JMX exporter provide an HTTP server that we need to expose outside of the pod for allowing a Prometheus server to pull metrics.

Some considerations : 
- using the "sidecar" solution, the exporter isn't able to get process metrics like CPU and memory which is possible if we use it as a Java agent.
- in both cases we should make available the HTTP server exposed by the exporter as a K8S/OS service for allowing connection from a Prometheus server. We don't need a single service because load balancing is not what we want; we want the Prometheus server getting metrics from each pod. It means that such services should be created by the cluster controller when the cluster is deployed.

I really like the "sidecar" approach because the two things (broker and exporter) are logically separated and some "failure" or crash in the agent can't kill the broker as well (which can happen if they run in the same container, same JVM). Of course we have the limitation of no system metrics.

At same time, the Prometheus server can be configured by user specifying the "targets" so the services names from which getting metrics or using a specific "kubernetes_sd_configs" section which allow the server to discovery all services in the deployment. Configuration is simpler but I haven't found any information about having some filter on such discovered services.

@tombentley @scholzj any thoughts ?

**Comment by scholzj** [comment]
Things to consider from my side ...
* How many resources does the sidecar need? If it is not significantly more expensive than the agent, we should probably use the sidecar.
* Does Prometheus really need us to create some services? I expected that it is able to find the pods  directly. But if needed we should be able to create the services.
* Is it only Pod CPU and memory metrics we are missing when we use the sidecar? Such metrics will be provided also by Kubernetes / OpenShift, so it should not be a problem. If we would be missing for example some JVM metrics, that might be bigger problem. 

Anyway, on the first look sidecar looks good, I agree.

**Comment by ppatierno** [comment]
> How many resources does the sidecar need? If it is not significantly more expensive than the agent, we should probably use the sidecar.

I think that the sidecar should be really light. Just the exporter which exposes a simple HTTP server but I have to dig into it for having some numbers.

> Does Prometheus really need us to create some services? I expected that it is able to find the pods directly. But if needed we should be able to create the services.

Well the Prometheus server, using the "kubernetes_sd_configs" section in the config file can set "role: pods" so maybe it is what we want but even in this case the user should be able to filter other pods in some way or at least at namespace level.

> Is it only Pod CPU and memory metrics we are missing when we use the sidecar?

I'm not a JMX expert, this limitation is explained in the official GitHub repo for the JMX exporter saying "unable to expose process metrics (e.g., memory and CPU usage)". I'll take a look at the code.

**Comment by tombentley** [comment]
The sidecar approach means at least another JVM (I assume the out-of-process exporter is a java program) with its footprint. With the agent approach the JVM is shared, so I'd expect that to use fewer resources. It would be useful to get an idea what the difference is.

**Comment by ppatierno** [comment]
Yes that's true I'm only scared about having some other "process" in the same container as the Kafka broker which could kill the broker itself if such "process" fails in the same JVM. Btw I'll dig into it ;)

**Comment by tombentley** [comment]
Yes, that *is* a possibility. What does their issue tracker look like (if it's full of bugs about the agent crashing the JVM then that's decision made, but if not then we should at least experiment a little with the agent). There is, perhaps, another upside to using the agent: If the process in the sidecar crashes won't we need to take special action to restart it? But if the broker crashes (because of the agent), it would be restarted for us by kubernetes. Maybe the special action is just a bash loop, but it's worth thinking about.

**Comment by scholzj** [comment]
For Kubernetes there is no hierarchy between the containers - both containers will have the same value for Kubernetes and will be treated the same way. So there will be no need for a special code to restart the sidecar.

**Comment by ppatierno** [comment]
@scholzj @tombentley about having the JMX exporter running inside a "sidecar" container so in the standalong HTTP server mode (as they called it), take a look to this issue and this PR : 

https://github.com/prometheus/jmx_exporter/issues/111

https://github.com/prometheus/jmx_exporter/pull/204

They were just updated about 10 days ago. The main committer seems to be not so supportive and he discourage to use the standalone mode.

Any thoughts ?

**Comment by ppatierno** [comment]
I had no clues from the main committer on why using the standalone mode is discouraged so I have decided to start adding metrics using the agent mode and it means that : 

- the Kafka base and Zookeeper Docker images are improved downloading the JMX exporter other than exposing a port for metrics (I used 9404 which I found as a sort of JMX exporter default port from Prometheus WiKi)
- an agent configuration file (YAML) is provided as default configuration file for exposed metrics (i.e in /opt/prometheus/config.yml). A user can change that in a similar fashion as we do with Kafka Connect for adding plugins (i.e. mounting a new volume in the above location with a different config.yml file containing the desired configuration). Another possibility could be using a ConfigMap (even for the provided default configuration) containing the exporter config file in the data section and then mounting it as volume inside the container. In this case, the user should just provide a different ConfigMap file.
- the agent is started through the `KAFKA_OPTS` env var (adding -javaagent: bla bla bla)

Do we want to make configurable having metrics (or not) exposed ? It's related to start the Java agent through the `KAFKA_OPTS` or not. It's should be possible using a parameter in the OpenShift template setting a corresponding env var but it's not possible on K8S. I guess that, about configurable parameters in K8S, we have a "hole" for other stuff (i.e. `KAFKA_DEFAULT_REPLICATION_FACTOR`) becaue we are not providing something like Helm for deploying on K8S. Is that right ?

Or do we just want metrics enabled by default without a way for disabling them when the cluster is deployed ?

@scholzj @tombentley wdyt ?

**Comment by scholzj** [comment]
> an agent configuration file (YAML) is provided as default configuration file for exposed metrics (i.e in /opt/prometheus/config.yml).

I would start with providing a default YAML file and that is it. Do we need to improve the default file to export some Kafka specific metrics (not just the JVM stuff which is the same for every Java application).

As a part of _cluster controller_ work we should decide how to pass some other than default value to the Pod. Config map or environment variable being our likely options.. What kind of changes do we expect the user to do?

> Do we want to make configurable having metrics (or not) exposed ? It's related to start the Java agent through the KAFKA_OPTS or not. It's should be possible using a parameter in the OpenShift template setting a corresponding env var but it's not possible on K8S. I guess that, about configurable parameters in K8S, we have a "hole" for other stuff (i.e. KAFKA_DEFAULT_REPLICATION_FACTOR) becaue we are not providing something like Helm for deploying on K8S. Is that right ?

I think we should have an option to switch it on/off. For k8s, I would expect that we should have the environment variable as part of the YAML file and users can change it manually before deploying. Helm is nice, but I'm not sure we really want to invest into that right now.

**Comment by scholzj** [comment]
I would assume that we can easily switch the metrics on/off depending on whether we deploy the cluster balancer. However this also means that we probably cannot give the user completely free hand to configure the exporter - because that might affect the metrics that the cluster balancer needs.

I wonder what is the difference between exporting some metrics and exporting all metrics in resource comsumption. AFAIK users can configure what Prometheus will consume on Prometheus side as well. So if the difference between all metrics and some metrics is negligible, we can always export all (eventually have the on/off switch) and let the users configure what metrics they want to receive on Prometheus side.

Another thought which comes to my mind ... I'm not sure whether Kafka gives you _network and disk load metrics_ I would expect that for such information you might need to go to Kubernetes / OpenShift it self.

**Comment by ppatierno** [comment]
The only way for Prometheus to "filter" metrics when the exporter provides the full "box" is just dropping and not storing them; it's not an ideal solution I think.

As discussed the solution could be : 
- providing the JMX exporter configuration through a ConfigMap which is mapped to volume in order to have the configuration accessible by the java agent
- the repo will provide a ConfigMap with some "default" metrics which could be "needed" metrics for handling cluster balancing for example
- the user can change/add metrics providing a ConfigMap which is handled by the cluster controller which takes care to create the final ConfigMap with "needed" metrics + user defined ones

**Comment by scholzj** [comment]
This has been mostly implemented and can be closed. Any remaining parts should be addressed in separate issues (such as #101).
